config/routes.rb
Rails.application.routes.draw do
  resources :initiatives
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/initiative.rb
class Initiative < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  before_action :set_initiative, only: %i[ show edit update destroy ]

  # GET /initiatives or /initiatives.json
  def index
    @initiatives = Initiative.all
  end

  # GET /initiatives/1 or /initiatives/1.json
  def show
  end

  # GET /initiatives/new
  def new
    @initiative = Initiative.new
  end

  # GET /initiatives/1/edit
  def edit
  end

  # POST /initiatives or /initiatives.json
  def create
    @initiative = Initiative.new(initiative_params)

    respond_to do |format|
      if @initiative.save
        format.html { redirect_to initiative_url(@initiative), notice: "Initiative was successfully created." }
        format.json { render :show, status: :created, location: @initiative }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initiatives/1 or /initiatives/1.json
  def update
    respond_to do |format|
      if @initiative.update(initiative_params)
        format.html { redirect_to initiative_url(@initiative), notice: "Initiative was successfully updated." }
        format.json { render :show, status: :ok, location: @initiative }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @initiative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiatives/1 or /initiatives/1.json
  def destroy
    @initiative.destroy

    respond_to do |format|
      format.html { redirect_to initiatives_url, notice: "Initiative was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initiative
      @initiative = Initiative.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def initiative_params
      params.require(:initiative).permit(:name, :category, :event_date, :participants_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.erb
<%= form_with(model: initiative) do |form| %>
  <% if initiative.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(initiative.errors.count, "error") %> prohibited this initiative from being saved:</h2>

      <ul>
        <% initiative.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :event_date, style: "display: block" %>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.label :participants_number, style: "display: block" %>
    <%= form.number_field :participants_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/initiatives/_initiative.html.erb
<div id="<%= dom_id initiative %>">
  <p>
    <strong>Name:</strong>
    <%= initiative.name %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= initiative.category %>
  </p>

  <p>
    <strong>Event date:</strong>
    <%= initiative.event_date %>
  </p>

  <p>
    <strong>Participants number:</strong>
    <%= initiative.participants_number %>
  </p>

</div>

app/views/initiatives/edit.html.erb
<h1>Editing initiative</h1>

<%= render "form", initiative: @initiative %>

<br>

<div>
  <%= link_to "Show this initiative", @initiative %> |
  <%= link_to "Back to initiatives", initiatives_path %>
</div>

app/views/initiatives/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Initiatives</h1>

<div id="initiatives">
  <% @initiatives.each do |initiative| %>
    <%= render initiative %>
    <p>
      <%= link_to "Show this initiative", initiative %>
    </p>
  <% end %>
</div>

<%= link_to "New initiative", new_initiative_path %>

app/views/initiatives/new.html.erb
<h1>New initiative</h1>

<%= render "form", initiative: @initiative %>

<br>

<div>
  <%= link_to "Back to initiatives", initiatives_path %>
</div>

app/views/initiatives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @initiative %>

<div>
  <%= link_to "Edit this initiative", edit_initiative_path(@initiative) %> |
  <%= link_to "Back to initiatives", initiatives_path %>

  <%= button_to "Destroy this initiative", @initiative, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>